CREATE DATABASE ESCUELA;

USE ESCUELA;

CREATE TABLE ALUMNO (
                        ID BIGINT NOT NULL AUTO_INCREMENT,
                        NOMBRE VARCHAR(100) NOT NULL,
                        EDAD INT NOT NULL,
                        PROMEDIO DECIMAL(4,2) NOT NULL,
                        PRIMARY KEY (ID)
);

CREATE TABLE PROFESOR
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    ESPECIALIDAD VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE MATERIA
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    CREDITOS INT NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE PROFESOR_MATERIA
(
    PROFESOR_ID BIGINT NOT NULL,
    MATERIA_ID BIGINT NOT NULL,
    PRIMARY KEY (PROFESOR_ID, MATERIA_ID),
    CONSTRAINT FK_PROFESOR_MATERIA_PROFESOR
        FOREIGN KEY (PROFESOR_ID)
            REFERENCES PROFESOR(ID),
    CONSTRAINT FK_PROFESOR_MATERIA_MATERIA
        FOREIGN KEY (MATERIA_ID)
            REFERENCES MATERIA(ID)
) ENGINE = InnoDB;

CREATE TABLE ALUMNO_MATERIA
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    ALUMNO_ID BIGINT NOT NULL,
    MATERIA_ID BIGINT NOT NULL,
    CALIFICACION DECIMAL(4,2),
    PRIMARY KEY (ID),
    CONSTRAINT UK_ALUMNO_MATERIA
        UNIQUE (ALUMNO_ID, MATERIA_ID),
    CONSTRAINT FK_ALUMNO_MATERIA_ALUMNO
        FOREIGN KEY (ALUMNO_ID)
            REFERENCES ALUMNO(ID),
    CONSTRAINT FK_ALUMNO_MATERIA_MATERIA
        FOREIGN KEY (MATERIA_ID)
            REFERENCES MATERIA(ID)
) ENGINE = InnoDB;

INSERT INTO ALUMNO (NOMBRE, EDAD, PROMEDIO)
VALUES
    ('ANA', 20, 9.50),
    ('CARLOS', 22, 8.70),
    ('MARIA', 19, 9.10);

INSERT INTO PROFESOR (NOMBRE, ESPECIALIDAD)
VALUES
    ('GERDOC GUTIERREZ', 'PROGRAMACION'),
    ('MARIA LOPEZ', 'BASES DE DATOS'),
    ('PEDRO RAMIREZ', 'MATEMATICAS'),
    ('ANA MARTINEZ', 'REDES');

INSERT INTO MATERIA (NOMBRE, CREDITOS)
VALUES
    ('PROGRAMACION ORIENTADA A OBJETOS', 8),
    ('BASES DE DATOS', 8),
    ('MATEMATICAS', 6),
    ('REDES DE COMPUTADORAS', 7),
    ('DESARROLLO WEB', 8);

INSERT INTO PROFESOR_MATERIA
(PROFESOR_ID, MATERIA_ID)
VALUES
    (1, 1),
    (1, 5),
    (2, 2),
    (3, 3),
    (4, 4);

INSERT INTO ALUMNO_MATERIA
(ALUMNO_ID, MATERIA_ID, CALIFICACION)
VALUES
    (1, 1, 9.50),
    (1, 2, 9.00),
    (1, 3, 8.50),
    (2, 1, 8.00),
    (2, 2, 8.70),
    (3, 3, 9.80),
    (3, 4, 9.20);